# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('maja_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFormPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('show_description', models.BooleanField(default=True, help_text="Show the mailing list's description.", verbose_name='show description')),
                ('mailing_list', models.ForeignKey(help_text='Mailing List to subscribe to.', on_delete=django.db.models.deletion.CASCADE, to='maja_newsletter.MailingList', verbose_name='mailing list')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
